version: "3.7"

services:
  grafana:
    container_name: grafana
    environment:
      - AWS_PROFILE=grafana
    image: grafana/grafana:7.0.0
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - $HOME/.aws/credentials:/usr/share/grafana/.aws/credentials

volumes:
  grafana:
