{
 "title": "AWS API Gateway",
 "description": "Visualize AWS API Gateway metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "apiname",
    "label": "ApiName",
    "query": "dimension_values($region,AWS/ApiGateway,Count,ApiName)"
   },
   {
    "name": "stage",
    "label": "AND Stage",
    "query": "dimension_values($region,AWS/ApiGateway,Count,Stage, {\"ApiName\": \"$apiname\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Latency / IntegrationLatency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "4XXError / 5XXError",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "e400",
     "item": { "filter": "" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "e500",
     "item": { "filter": "" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Total Error Rate",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "expression": "SUM([e400,e500])*100/countt",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "rate",
     "item": { "filter": "" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "CacheHitCount / CacheMissCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}