{
 "title": "AWS Route 53",
 "description": "Visualize AWS Route 53 metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "healthcheckid",
    "label": "HealthCheckId",
    "query": "dimension_values($region,AWS/Route53,HealthCheckStatus, HealthCheckId)"
   }
  ]
 },
 "panels": [
  {
   "title": "HealthCheckPercentageHealthy / ChildHealthCheckHealthyCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthCheckPercentageHealthy",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ChildHealthCheckHealthyCount",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ConnectionTime / TimeToFirstByte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConnectionTime",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TimeToFirstByte",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthCheckStatus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthCheckStatus",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "SSLHandshakeTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SSLHandshakeTime",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}